"""
Cloud Watcher - Platinum Tier
24/7 always-on watcher for Cloud VM

Responsibilities:
- Monitor Gmail for new emails (draft replies only)
- Monitor social media for engagement (draft posts only)
- Create draft files in /Pending_Approval/
- Write updates to /Updates/ for Local agent
- NEVER send emails or post directly (draft-only)

Usage:
    python cloud_watcher.py
"""

import logging
import time
import json
from pathlib import Path
from datetime import datetime
from abc import ABC, abstractmethod

# Vault paths
VAULT_ROOT = Path(__file__).parent.resolve()
NEEDS_ACTION = VAULT_ROOT / "Needs_Action"
PENDING_APPROVAL = VAULT_ROOT / "Pending_Approval"
UPDATES = VAULT_ROOT / "Updates"
IN_PROGRESS = VAULT_ROOT / "In_Progress" / "cloud"
LOGS = VAULT_ROOT / "Logs"

# Ensure directories exist
for d in [NEEDS_ACTION, PENDING_APPROVAL, UPDATES, IN_PROGRESS, LOGS]:
    d.mkdir(parents=True, exist_ok=True)

# Configure logging
log_file = LOGS / f"cloud_watcher_{datetime.now():%Y-%m-%d}.log"
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(log_file, encoding="utf-8"),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)


class BaseCloudWatcher(ABC):
    """Base class for all cloud watchers."""
    
    def __init__(self, check_interval: int = 60):
        self.check_interval = check_interval
        self.processed_ids = set()
        self.state_file = VAULT_ROOT / f".{self.__class__.__name__}_state.json"
        self.load_state()
    
    def load_state(self):
        """Load processed IDs from state file."""
        if self.state_file.exists():
            try:
                data = json.loads(self.state_file.read_text(encoding="utf-8"))
                self.processed_ids = set(data.get("processed_ids", []))
            except (json.JSONDecodeError, OSError):
                pass
    
    def save_state(self):
        """Save processed IDs to state file."""
        data = {"processed_ids": list(self.processed_ids)}
        self.state_file.write_text(json.dumps(data, indent=2), encoding="utf-8")
    
    @abstractmethod
    def check_for_updates(self) -> list:
        """Return list of new items to process."""
        pass
    
    @abstractmethod
    def create_draft(self, item) -> Path:
        """Create draft file in /Pending_Approval/."""
        pass
    
    def claim_task(self, task_file: str) -> bool:
        """
        Claim a task by moving it to /In_Progress/cloud/
        Returns True if successfully claimed, False if already claimed.
        """
        source = NEEDS_ACTION / task_file
        dest = IN_PROGRESS / task_file
        
        if not source.exists():
            return False
        
        try:
            source.rename(dest)
            logger.info(f"Claimed task: {task_file}")
            return True
        except Exception as e:
            logger.warning(f"Failed to claim task {task_file}: {e}")
            return False
    
    def write_update(self, update_type: str, data: dict):
        """Write update to /Updates/ for Local agent."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{update_type}_{timestamp}.md"
        filepath = UPDATES / filename
        
        content = f"""---
type: {update_type}
timestamp: {datetime.now().isoformat()}
agent: cloud
---

# Cloud Agent Update

## Type: {update_type}

## Data
{json.dumps(data, indent=2)}

---
*Generated by cloud_watcher.py*
"""
        filepath.write_text(content, encoding="utf-8")
        logger.info(f"Update written: {filename}")
    
    def run(self):
        """Main watcher loop."""
        logger.info(f"Starting {self.__class__.__name__} (Cloud)")
        logger.info(f"Check interval: {self.check_interval}s")
        
        while True:
            try:
                items = self.check_for_updates()
                for item in items:
                    self.create_draft(item)
            except Exception as e:
                logger.error(f"Error in watcher: {e}")
            finally:
                self.save_state()
                time.sleep(self.check_interval)


class GmailCloudWatcher(BaseCloudWatcher):
    """
    Gmail Watcher for Cloud VM
    - Polls Gmail every 5 minutes
    - Creates draft replies in /Pending_Approval/email/
    - NEVER sends directly (draft-only)
    """
    
    def __init__(self, check_interval: int = 300):
        super().__init__(check_interval)
        self.email_domain = NEEDS_ACTION / "email"
        self.email_domain.mkdir(exist_ok=True)
    
    def check_for_updates(self) -> list:
        """
        Check Gmail for new emails.
        In production, this would use Gmail API.
        For now, returns empty list (API integration required).
        """
        logger.debug("Checking Gmail for new messages...")
        # TODO: Implement Gmail API integration
        # return gmail_service.get_unread_emails()
        return []
    
    def create_draft(self, email_data: dict) -> Path:
        """Create email draft in /Pending_Approval/email/"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"EMAIL_{email_data.get('id', 'unknown')}_{timestamp}.md"
        filepath = PENDING_APPROVAL / "email" / filename
        
        content = f"""---
type: email_draft
from: {email_data.get('from', 'Unknown')}
subject: {email_data.get('subject', 'No Subject')}
received: {email_data.get('date', datetime.now().isoformat())}
priority: {email_data.get('priority', 'normal')}
status: pending_approval
agent: cloud
created: {datetime.now().isoformat()}
---

# Email Draft (Cloud Agent)

## Original Message
**From:** {email_data.get('from', 'Unknown')}
**Subject:** {email_data.get('subject', 'No Subject')}
**Date:** {email_data.get('date', 'Unknown')}

---
**Content:**

{email_data.get('body', '')}

---

## Suggested Reply (Draft - Requires Local Approval)

{email_data.get('suggested_reply', 'Draft reply not generated yet.')}

---

## Action Required
Move this file to `/Approved` to send the reply.
Delete or move to `/Rejected` to discard.

---
*Generated by cloud_watcher.py (Platinum Tier)*
"""
        filepath.write_text(content, encoding="utf-8")
        
        # Write update for Local agent
        self.write_update("email_draft", {
            "email_id": email_data.get('id'),
            "from": email_data.get('from'),
            "subject": email_data.get('subject'),
            "filepath": str(filepath),
        })
        
        logger.info(f"Email draft created: {filename}")
        return filepath


class SocialCloudWatcher(BaseCloudWatcher):
    """
    Social Media Watcher for Cloud VM
    - Monitors for engagement opportunities
    - Creates draft posts in /Pending_Approval/social/
    - NEVER posts directly (draft-only)
    """
    
    def __init__(self, check_interval: int = 600):
        super().__init__(check_interval)
        self.social_domain = NEEDS_ACTION / "social"
        self.social_domain.mkdir(exist_ok=True)
    
    def check_for_updates(self) -> list:
        """
        Check social media for engagement opportunities.
        In production, this would use social media APIs.
        For now, returns empty list (API integration required).
        """
        logger.debug("Checking social media for opportunities...")
        # TODO: Implement social media API integration
        # return social_api.get_engagement_opportunities()
        return []
    
    def create_draft(self, post_data: dict) -> Path:
        """Create social post draft in /Pending_Approval/social/"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        platform = post_data.get('platform', 'unknown')
        filename = f"SOCIAL_{platform}_{timestamp}.md"
        filepath = PENDING_APPROVAL / "social" / filename
        
        content = f"""---
type: social_post_draft
platform: {platform}
content_type: {post_data.get('content_type', 'post')}
status: pending_approval
agent: cloud
created: {datetime.now().isoformat()}
---

# Social Media Post Draft (Cloud Agent)

## Platform: {platform}

## Suggested Content

{post_data.get('content', '')}

## Hashtags
{', '.join(post_data.get('hashtags', []))}

## Media Attachments
{post_data.get('media', 'None')}

---

## Action Required
Move this file to `/Approved` to publish.
Delete or move to `/Rejected` to discard.

---
*Generated by cloud_watcher.py (Platinum Tier)*
"""
        filepath.write_text(content, encoding="utf-8")
        
        # Write update for Local agent
        self.write_update("social_draft", {
            "platform": platform,
            "content_preview": post_data.get('content', '')[:100],
            "filepath": str(filepath),
        })
        
        logger.info(f"Social draft created: {filename}")
        return filepath


class AccountingCloudWatcher(BaseCloudWatcher):
    """
    Accounting Watcher for Cloud VM
    - Monitors Odoo for new transactions
    - Creates draft categorizations in /Pending_Approval/accounting/
    - NEVER posts payments (draft-only)
    """
    
    def __init__(self, check_interval: int = 300):
        super().__init__(check_interval)
        self.accounting_domain = NEEDS_ACTION / "accounting"
        self.accounting_domain.mkdir(exist_ok=True)
    
    def check_for_updates(self) -> list:
        """
        Check Odoo for new transactions.
        In production, this would use Odoo JSON-RPC API.
        For now, returns empty list (API integration required).
        """
        logger.debug("Checking Odoo for new transactions...")
        # TODO: Implement Odoo API integration
        # return odoo_api.get_new_transactions()
        return []
    
    def create_draft(self, transaction_data: dict) -> Path:
        """Create accounting draft in /Pending_Approval/accounting/"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"ACCOUNTING_{transaction_data.get('id', 'unknown')}_{timestamp}.md"
        filepath = PENDING_APPROVAL / "accounting" / filename
        
        content = f"""---
type: accounting_draft
transaction_type: {transaction_data.get('type', 'unknown')}
amount: {transaction_data.get('amount', 0)}
date: {transaction_data.get('date', 'Unknown')}
status: pending_approval
agent: cloud
created: {datetime.now().isoformat()}
---

# Accounting Entry Draft (Cloud Agent)

## Transaction Details
- **Type:** {transaction_data.get('type', 'Unknown')}
- **Amount:** ${transaction_data.get('amount', 0):.2f}
- **Date:** {transaction_data.get('date', 'Unknown')}
- **Description:** {transaction_data.get('description', '')}

## Suggested Categorization (Draft - Requires Local Approval)
- **Category:** {transaction_data.get('category', 'Uncategorized')}
- **Account:** {transaction_data.get('account', 'Unknown')}

---

## Action Required
Move this file to `/Approved` to post the entry.
Delete or move to `/Rejected` to discard.

---
*Generated by cloud_watcher.py (Platinum Tier)*
"""
        filepath.write_text(content, encoding="utf-8")
        
        # Write update for Local agent
        self.write_update("accounting_draft", {
            "transaction_id": transaction_data.get('id'),
            "type": transaction_data.get('type'),
            "amount": transaction_data.get('amount'),
            "filepath": str(filepath),
        })
        
        logger.info(f"Accounting draft created: {filename}")
        return filepath


def main():
    """Start all cloud watchers."""
    logger.info("=" * 60)
    logger.info("Cloud Watcher Starting (Platinum Tier)")
    logger.info(f"Vault root: {VAULT_ROOT}")
    logger.info("=" * 60)
    
    watchers = [
        GmailCloudWatcher(check_interval=300),  # 5 minutes
        SocialCloudWatcher(check_interval=600),  # 10 minutes
        AccountingCloudWatcher(check_interval=300),  # 5 minutes
    ]
    
    # Start all watchers
    for watcher in watchers:
        logger.info(f"Starting {watcher.__class__.__name__}")
    
    try:
        while True:
            for watcher in watchers:
                try:
                    items = watcher.check_for_updates()
                    for item in items:
                        watcher.create_draft(item)
                except Exception as e:
                    logger.error(f"Error in {watcher.__class__.__name__}: {e}")
                finally:
                    watcher.save_state()
            time.sleep(60)
    except KeyboardInterrupt:
        logger.info("Cloud Watcher stopped by user.")


if __name__ == "__main__":
    main()
